### ISSUE TITLE
Can not parse contains method

### ISSUE THREAD

**Issue by hwy425** [TrigerSoft/jaque#14]
I pre-defined  a list as below
        List<Integer> list = new ArrayList<Integer>();
        list.add(new Integer(1));
        list.add(new Integer(2));
        list.add(new Integer(3)); 
the i get an expression example : obj => list.contains(obj.Value)

Exception happend

**Comment by kostat** [comment]
I created a small test case based on your description, which does not throw:

```java
static class IntHolder {
	public Integer Value;
}

@Test
public void testList() {

	List<Integer> list = new ArrayList<>();
	list.add(new Integer(1));
	list.add(new Integer(2));
	list.add(new Integer(3));

	Predicate<IntHolder> p = ensureSerializable(obj -> list.contains(obj.Value));
	final LambdaExpression<Predicate<IntHolder>> ex = LambdaExpression.parse(p);
}
```
Can you post the exact code snippet that fails for you? Exception stack trace?

**Comment by kostat** [comment]
In case the problem still exists, please provide the requested information and reopen the issue.

**Comment by hwy425** [comment]
ensureSerializable   how does this method work ? Its actually here i will get a null reference exception.

**Comment by hwy425** [comment]
Exception in thread "main" java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at demacia.helper.ToSqlVisitor.visit(ToSqlVisitor.java:83)
	at demacia.helper.ToSqlVisitor.visit(ToSqlVisitor.java:15)
	at com.trigersoft.jaque.expression.MemberExpression.visit(MemberExpression.java:70)
	at com.trigersoft.jaque.expression.Expression.accept(Expression.java:1443)
	at demacia.helper.ToSqlVisitor.visit(ToSqlVisitor.java:51)
	at demacia.helper.ToSqlVisitor.visit(ToSqlVisitor.java:15)
	at com.trigersoft.jaque.expression.InvocationExpression.visit(InvocationExpression.java:50)
	at com.trigersoft.jaque.expression.Expression.accept(Expression.java:1443)
	at demacia.helper.ToSqlVisitor.visit(ToSqlVisitor.java:57)
	at demacia.helper.ToSqlVisitor.visit(ToSqlVisitor.java:15)
	at com.trigersoft.jaque.expression.LambdaExpression.visit(LambdaExpression.java:111)
	at com.trigersoft.jaque.expression.Expression.accept(Expression.java:1443)
	at demacia.helper.ToSqlVisitor.visit(ToSqlVisitor.java:51)
	at demacia.helper.ToSqlVisitor.visit(ToSqlVisitor.java:15)
	at com.trigersoft.jaque.expression.InvocationExpression.visit(InvocationExpression.java:50)
	at com.trigersoft.jaque.expression.Expression.accept(Expression.java:1443)
	at demacia.helper.ToSqlVisitor.visit(ToSqlVisitor.java:57)
	at demacia.helper.ToSqlVisitor.visit(ToSqlVisitor.java:15)
	at com.trigersoft.jaque.expression.LambdaExpression.visit(LambdaExpression.java:111)
	at com.trigersoft.jaque.expression.Expression.accept(Expression.java:1443)
	at demacia.helper.Lambda2Sql.toPredicateSql(Lambda2Sql.java:32)
	at test.TestApp.getPredicateSQL(TestApp.java:44)
	at test.TestApp.main(TestApp.java:33)

**Comment by hwy425** [comment]
I copied ur test , when ExpressionClassVisitor setResult, an exception accured : "Method threw 'java/.lang.IndexOutOfBoundException' exception, Cannot evaluate com.trigerdoft.jaque.expression.InvocationExpression.toString()" @kostat

**Comment by kostat** [comment]
@hwy425:

1. I updated the sample and included `ensureSerializable`
2. From the stack trace you posted I can see that there is an NPE thrown in `demacia.helper.ToSqlVisitor.visit`. Please explain how it's related to JaQue.
3. Regarding `IndexOutOfBoundException` - since you put a breakpoint inside the library before the object is fully built, this causes an invalid state.

**In order to be productive, please post a compiling test case showing the problem.**
