### ISSUE TITLE
toString of a compound expression fails with an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by tomwhoiscontrary** [TrigerSoft/jaque#3]
Here's a test which i think should pass:

```java
	interface SerializableFunction<T, R> extends Serializable, Function<T, R> {};

	@Test
	public void canToStringACompoundExpression() throws Exception {
		SerializableFunction<String, String> e = s -> s.substring(0, 1).toUpperCase();
		Expression body = LambdaExpression.parse(e).getBody();
		Assert.assertEquals("P0.substring(0, 1).toUpperCase()", body.toString());
	}
```

Using release 2.1.0, this fails with:

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.Arrays$ArrayList.get(Arrays.java:3835)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1369)
	at com.trigersoft.jaque.expression.InstanceAdaptor.visit(InstanceAdaptor.java:42)
	at com.trigersoft.jaque.expression.InstanceAdaptor.visit(InstanceAdaptor.java:26)
	at com.trigersoft.jaque.expression.ParameterExpression.visit(ParameterExpression.java:50)
	at com.trigersoft.jaque.expression.Expression.accept(Expression.java:1443)
	at com.trigersoft.jaque.expression.SimpleExpressionVisitor.visitExpressionList(SimpleExpressionVisitor.java:44)
	at com.trigersoft.jaque.expression.InstanceAdaptor.visit(InstanceAdaptor.java:52)
	at com.trigersoft.jaque.expression.InstanceAdaptor.visit(InstanceAdaptor.java:26)
	at com.trigersoft.jaque.expression.InvocationExpression.visit(InvocationExpression.java:50)
	at com.trigersoft.jaque.expression.Expression.accept(Expression.java:1443)
	at com.trigersoft.jaque.expression.SimpleExpressionVisitor.visit(SimpleExpressionVisitor.java:109)
	at com.trigersoft.jaque.expression.SimpleExpressionVisitor.visit(SimpleExpressionVisitor.java:30)
	at com.trigersoft.jaque.expression.MemberExpression.visit(MemberExpression.java:70)
	at com.trigersoft.jaque.expression.Expression.accept(Expression.java:1443)
	at com.trigersoft.jaque.expression.InstanceAdaptor.normalize(InstanceAdaptor.java:37)
	at com.trigersoft.jaque.expression.InvocationExpression.toString(InvocationExpression.java:107)
```

I don't actually care about toStringing expressions, but i was doing it for debugging and it blew up. It suggests that there is a deeper problem, with InstanceAdaptor. I don't understand what's going on in the code here, but in InstanceAdaptor there is a method:

```java
	@Override
	public Expression visit(ParameterExpression e) {
		Expression x = args.get(e.getIndex());
		if (x instanceof ParameterExpression
				&& ((ParameterExpression) x).getIndex() == e.getIndex())
			return e;
		return x;
	}
```

And here, args is an empty list, but e.getIndex() is 0. I assume this particular expression describes to the invocation of toUpperCase(), and i would guess that there is a mismatch between the number of formal parameters at the language level (zero) and the number at the bytecode level (one, for this).

**Comment by tomwhoiscontrary** [comment]
:ok_hand:
